spring.application.name=stylehub-store

spring.datasource.url=jdbc:mysql://localhost:3306/bwabh_alabtkar_db
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379


resend.api-key=re_cnHognd4_Njz3tb8wS6gMazSx5MZT6zYG

logging.level.org.springframework.security=DEBUG