
spring.datasource.url=jdbc:postgresql://ep-sweet-water-axwtfsra-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_P5bFl7KMiqAu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379


resend.api-key=re_cnHognd4_Njz3tb8wS6gMazSx5MZT6zYG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omarharaz553@gmail.com
spring.mail.password=dtcmfznhiiotjles


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8



logging.level.org.springframework.security=DEBUG